# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AI융합연구실
short_labname: DjuAILab
email: djuailab@gmail.com
logo: logo.png
description: > # 다음 줄에 연구실 소개 입력
  DjuAILab of Aartificial intelligence, Daejeon University; 대전대학교 SW융합대학 홍용근 교수 AI융합 연구실; Yonggeun Hong;
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  djuailab
google-site-verification:

# Build settings
markdown: kramdown
include: ['_pages', '_news']
plugins: [jekyll-seo-tag,jekyll-paginate]

paginate: 5
paginate_path: "/news/page:num/"
